pipeline:
  state_db: state/state.db

  source:
    module: prtimes
    keywords:
      - 試食会
    industries:
      - レストラン
      - カフェ
      - ホテル
      - 食品
      - 飲食
      - ビストロ
      - バー
      - 居酒屋

  filters:
    - module: yotei

  outputs:
    - module: ical
      output_path: docs/calendar.ics

    - module: json
      output_path: docs/feed.json
